


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hatcher-db
    username: postgres
    password: 123Mudar
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  
                
security:
  jwt:
    token:
      secret-key: 8xATUx4r2L52
      expire-length: 604800000 #1 week









